export const technicalSkills = [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "HTML/CSS",
    "React",
    "Node.js",
    "Angular",
    "Vue.js",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "SQL",
    "MongoDB",
    "Firebase",
    "Django",
    "Ruby on Rails",
    "ASP.NET",
    "Spring Boot",
    "Flutter",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "Git",
    "Jenkins",
    "CI/CD",
    "RESTful API",
    "GraphQL",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Big Data",
    "Blockchain",
    "Cybersecurity",
    "DevOps",
    "UI/UX Design",
    "Responsive Web Design",
    "Mobile App Development",
    "Web Development",
    "Game Development",
    "Embedded Systems",
    "IoT (Internet of Things)",
    "Robotics",
    "AR/VR Development",
    "Cloud Computing",
    "Linux Administration",
    "Windows Administration",
    "Network Administration",
    "Database Administration",
    "System Architecture",
    "Microservices",
    "Agile Methodologies",
    "Scrum",
    "TDD (Test-Driven Development)",
    "CI/CD Pipelines",
    "Blockchain Development",
    "Natural Language Processing",
    "Computer Vision",
    "UX Research",
    "Front-end Development",
    "Back-end Development",
    "Full-stack Development",
    "Mobile Application Development",
    "Data Analysis",
    "Data Visualization",
    "Deep Learning",
    "Neural Networks",
    "Cloud Security",
    "Serverless Computing",
    "Data Warehousing",
    "Game Design",
    "Quality Assurance (QA)",
    "Shell Scripting",
    "Object-Oriented Programming (OOP)",
    "Functional Programming",
    "Software Development Life Cycle (SDLC)",
    "Web Security",
    "Penetration Testing",
    "Vulnerability Assessment",
    "IT Support",
    "Technical Writing",
    "Version Control",
    "Continuous Integration",
    "Micro Frontends",
    "Blockchain Security",
    "Quantum Computing",
    "Bioinformatics",
    "Geographic Information Systems (GIS)",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Autonomous Vehicles",
    "Edge Computing",
    "Server Administration",
    "API Design",
    "Cloud Architecture",
    "Human-Computer Interaction (HCI)",
];


export const locations = ['Delhi', 'Mumbai', 'Bengaluru', 'Bengaluru/Bangalore', 'Bangalore', 'Chennai', 'Kolkata', 'Hyderabad', 'Pune', 'Ahmedabad', 'Noida', 'Gurgaon', 'Gurugram', 'Jaipur', 'Lucknow', 'Kanpur',
    'Nagpur', 'Indore', 'Patna', 'Chandigarh', 'Coimbatore', 'Vadodara', 'Ludhiana', 'Agra', 'Kochi', 'Surat', 'Visakhapatnam', 'Bhopal', 'Amritsar', 'Raipur', 'Ranchi', 'Varanasi', 'Jodhpur', 'Udaipur', 'Shimla', 'Manali', 'Mysuru/Mysore', 'Goa', 'Kochi',
    'Thiruvananthapuram', 'Ooty'];

